-- Drop the database if it exists
DROP DATABASE IF EXISTS postgres;

-- Create the database
CREATE DATABASE postgres;

-- Connect to the newly created database
\c postgres

-- Drop the factoids table if it exists
DROP TABLE IF EXISTS factoids;

-- Create the factoids table
CREATE TABLE factoids (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    factoid TEXT NOT NULL UNIQUE,
    createdDate DATE NOT NULL DEFAULT NOW(),
    votes INTEGER NOT NULL
);
