-- Drop the database if it exists
DROP DATABASE IF EXISTS postgres;

-- Create the database
CREATE DATABASE postgres;

-- Connect to the newly created database
\c postgres

-- Drop the factoids table if it exists
DROP TABLE IF EXISTS factoids;

-- Create the factoids table
CREATE TABLE factoids (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    factoid TEXT NOT NULL UNIQUE,
    createdDate DATE NOT NULL DEFAULT NOW(),
    votes INTEGER NOT NULL
);

-- Drop the users table if it exists
DROP TABLE IF EXISTS users;

-- Create the users table
CREATE TABLE users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    dob DATE NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    registrationDate DATE NOT NULL DEFAULT NOW()
);

-- Drop the user_roles table if it exists
DROP TABLE IF EXISTS user_roles;

-- Create the user_roles table
CREATE TABLE user_roles (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id integer REFERENCES users(id),
    role VARCHAR(255)[]
);